### ISSUE TITLE
Desk not moving

### ISSUE THREAD

**Issue by fritz92philipp** [jechtom/linak-desk-client#2]
Hello,
I have the problem that the desk only responds to the commands if the original "Linak Desk Control Program" was connected before. 

The program does not get any response at the following command:
await DpgCommandDispatcher.InvokeGetCapabilitiesAsync();

It seems that the original program sends a clear command or something else.

I have the DPG1M unit.

Thanks a lot

**Comment by fritz92philipp** [comment]
I found a Solution:

Before getting the Capabilities (await DpgCommandDispatcher.InvokeGetCapabilitiesAsync()) is needed to send the following Bytes:

`
DpgCommandTypes.INIT = 134,
`

```
byte[] initBytes = new byte[] {
    (byte)(1 >> 32),
    (byte)(1 >> 64),
    (byte)(1 >> 96),
    (byte)(1 >> 128),
    (byte)(1 >> 160),
    (byte)(1 >> 192),
    (byte)(1 >> 224),
    (byte)(1 >> 256),
    (byte)(1 >> 288),
    (byte)(1 >> 320),
    (byte)(1 >> 352),
    (byte)(1 >> 384),
    (byte)(1 >> 416),
    (byte)(1 >> 448),
    (byte)(1 >> 480),
    (byte)(1 >> 512),
    (byte)(1 >> 544)
};
byte[] initCommand = BuildCommandRequestWrite(DpgCommandTypes.INIT, initBytes);
await InvokeCommandAsync(initCommand);
```

           
After that, the Desk moving without opening the original "Linak Desk Control" Program

**Comment by jechtom** [comment]
That is good to know! Thanks. I was unable to verify it without new table.
